version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3006:3006'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - test-network
    restart: always

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: db
      POSTGRES_PASSWORD: test
    networks:
      - test-network

networks:
  test-network:
    name: test-network
    driver: bridge

volumes:
  data:
  node_modules:
